/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ImportacoesRouteImport } from './routes/importacoes'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as JaPagosRouteImport } from './routes/ja-pagos'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes/$clienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesRoute = ImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const JaPagosRoute = JaPagosRouteImport.update({
  id: '/ja-pagos',
  path: '/ja-pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacoes': typeof ImportacoesRoute
  '/importar': typeof ImportarRoute
  '/ja-pagos': typeof JaPagosRoute
  '/pagamentos': typeof PagamentosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacoes': typeof ImportacoesRoute
  '/importar': typeof ImportarRoute
  '/ja-pagos': typeof JaPagosRoute
  '/pagamentos': typeof PagamentosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacoes': typeof ImportacoesRoute
  '/importar': typeof ImportarRoute
  '/ja-pagos': typeof JaPagosRoute
  '/pagamentos': typeof PagamentosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/configuracoes'
    | '/importacoes'
    | '/importar'
    | '/ja-pagos'
    | '/pagamentos'
    | '/clientes/$clienteId'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/configuracoes'
    | '/importacoes'
    | '/importar'
    | '/ja-pagos'
    | '/pagamentos'
    | '/clientes/$clienteId'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/analise'
    | '/configuracoes'
    | '/importacoes'
    | '/importar'
    | '/ja-pagos'
    | '/pagamentos'
    | '/clientes/$clienteId'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseRoute: typeof AnaliseRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ImportacoesRoute: typeof ImportacoesRoute
  ImportarRoute: typeof ImportarRoute
  JaPagosRoute: typeof JaPagosRoute
  PagamentosRoute: typeof PagamentosRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes': {
      id: '/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof ImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja-pagos': {
      id: '/ja-pagos'
      path: '/ja-pagos'
      fullPath: '/ja-pagos'
      preLoaderRoute: typeof JaPagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseRoute: AnaliseRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ImportacoesRoute: ImportacoesRoute,
  ImportarRoute: ImportarRoute,
  JaPagosRoute: JaPagosRoute,
  PagamentosRoute: PagamentosRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
