/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JaPagosRouteImport } from './routes/ja-pagos'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes/$clienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JaPagosRoute = JaPagosRouteImport.update({
  id: '/ja-pagos',
  path: '/ja-pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ja-pagos': typeof JaPagosRoute
  '/pagamentos': typeof PagamentosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ja-pagos': typeof JaPagosRoute
  '/pagamentos': typeof PagamentosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ja-pagos': typeof JaPagosRoute
  '/pagamentos': typeof PagamentosRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ja-pagos' | '/pagamentos' | '/clientes/$clienteId' | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ja-pagos' | '/pagamentos' | '/clientes/$clienteId' | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/ja-pagos'
    | '/pagamentos'
    | '/clientes/$clienteId'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JaPagosRoute: typeof JaPagosRoute
  PagamentosRoute: typeof PagamentosRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja-pagos': {
      id: '/ja-pagos'
      path: '/ja-pagos'
      fullPath: '/ja-pagos'
      preLoaderRoute: typeof JaPagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JaPagosRoute: JaPagosRoute,
  PagamentosRoute: PagamentosRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
